### PR TITLE
 Use default remote branch instead of `master`

### PR DESCRIPTION
**Pull request by 9999years**
Default to cloning the template repository's default branch, instead of hard-coding a default of `master` if `--branch` isn't given.

This has two benefits:

1. For repositories with a default branch other than `master`, `--branch` is no longer required when using `cargo generate`
2. If the user has `init.defaultBranch` ([new in Git 2.28.0](https://github.blog/2020-07-27-highlights-from-git-2-28/)) set to something other than `master`, the newly-created repository has that branch name.

As an added bonus, ~~when I~~ if a user with `init.defaultBranch` set to something other than `master` runs the integration tests, they don't all fail because the `master` branch can't be found.

(Re-do of #240 with renamed branch)

### CODE REVIEW

**Review by k0pernicus — APPROVED** [review]
I am ok with the changes - thanks @9999years for proposing those.

This will need another review anyway.
@EverlastingBugstopper, @ashleygwilliams ?

**Comment by sassman** [comment]
Any updates on the additional review? I'm in favor of getting that merged.

**Comment by k0pernicus** [comment]
@sassman I am in favor of getting that merged too :+1:

**Comment by k0pernicus** [comment]
@sassman I will update the MR to match the current master, and merge this as soon as the tests are fine.

**Comment by k0pernicus** [comment]
Done, thanks @9999years for your work :)

**Pull request merged**
