### PR TITLE
Update the project to the latest world version

### LINKED ISSUE #238: Update to the latest world version
The world has gone so far ahead that we should catch up with its new breaking changes!

### PR DESCRIPTION
**Pull request by Veetaha**
Closes #238 

* Update all dependencies versions to latest ones
* Replace `rustfmt-preview` with `rustfmt`
* Replace `failure` with `anyhow`
* Remove `quicli` completely
* Update cargo authors copied code to latest cargo master
* Fix clippy lints:
  * Replace &PathBuf to &Path in code
  * Remove bare `use crate_name` entires
  * Replace unexported `pub` with `pub(crate)`
* Apply some cosmetic impl refactorings

### CODE REVIEW

**Comment by Veetaha** [comment]
I have replaced `file://` with `file:///` in a test for git submodules because cargo no longer tolerates this syntax, see my comment here: https://github.com/rust-lang/cargo/pull/7238#issuecomment-667575236

**Comment by k0pernicus** [comment]
Awesome @Veetaha, thanks a lot for your big update 🎉 

Sounds good to me :)

@EverlastingBugstopper I think this should be the start of a new git tag, what do you think?

**Review by k0pernicus — APPROVED** [review]

**Comment by k0pernicus** [comment]
In my opinion, this should be the last commit before the next version release...

@sassman What do you think about that?
Do we attempt to work on https://github.com/ashleygwilliams/cargo-generate/pull/205 before merging those big changes?

**Comment by sassman** [comment]
@k0pernicus as it seems there is more cleanup work to do in #205 
So I'd suggest getting this bigger one upstreamed, then I would rebase and work thru the changes needed to get #205 on the street. But release related, I would opt for releasing without #205 to not delay a release further. IMO there are good helpful features / fixes already there that justify a new release, #205 can be a followup release.

**Comment by Veetaha** [comment]
Rebased

**Comment by k0pernicus** [comment]
Great, thanks!

I will check this as soon as https://github.com/ashleygwilliams/cargo-generate/pull/242 is fine.

**Comment by k0pernicus** [comment]
@Veetaha Is it possible to rebase with the latest master changes please?
Thanks in advance :)

**Comment by Veetaha** [comment]
Done

**Review by sassman — APPROVED** [review]
👍

**Comment by k0pernicus** [comment]
Thanks again for your (big) contribution @Veetaha :)

**Pull request merged**
