### PR TITLE
Fix/submodules init

### PR DESCRIPTION
**Pull request by k0pernicus**
This pull request is a proposition for issue #83.

Allow to initialize and update a git submodule from a given template repository.

This feature has been tested manually ( we need tests here - I am open to any proposals and ideas in the establishment of these tests :) ) in cloning a cargo template from:

* [rocket-base](https://github.com/k0pernicus/cargo-template-rocket-base),
* [a toy submodule git repository](https://github.com/k0pernicus/cargo-template-test-submodule).

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
not super sure how we want to go about testing this- it's a bit complicated. let's open up an issue to discuss test strategy. i'll manually test this as well, and perhaps we can get this out and get tests going after the release

**Comment by ashleygwilliams** [comment]
about to test this locally, one thing i realized- would you mind adding a commit that explains how to use this in the README? thanks again for all your efforts today! really awesome and helpful! thank you!

**Comment by k0pernicus** [comment]
No problem :)
I'm getting to work on it.

**Comment by ashleygwilliams** [comment]
tested locally, works great! awesome job @k0pernicus - i'll wait on the docs commit but once that's done i think we're good to merge!

**Comment by ashleygwilliams** [comment]
also- i just realized! it's very late where you are- it's even a little late for me. please don't feel you need to rush. i'm happy to just do the release tomorrow :)

**Comment by k0pernicus** [comment]
@ashleygwilliams No problem for me, I am very happy to help :)  
I added a dedicated section in CONTRIBUTING.md, for testing the code.
However, I'm not so sure of my English :/

I included the manual tests in this section.  
Are you ok with that?

Also, I can refer the CONTRIBUTING page from the README page if you want to :)

**Pull request merged**
