### PR TITLE
Adding branches to template repository pulls

### PR DESCRIPTION
**Pull request by deg4uss3r**
This is a work in progress (WIP) PR for Issue #71  

PS- Sorry was on holiday :)

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
no sorry necessary! hope you had a nice holiday :)

**Comment by deg4uss3r** [comment]
Hey! Almost done here, but I couldn't reproduce the non-zero exit code from `cargo fmt --all -- --check` locally with the same call or with `rustfmt --check`.

**Comment by DD5HT** [comment]
@deg4uss3r did you read [this](https://github.com/ashleygwilliams/cargo-generate/blob/master/CONTRIBUTING.md)? you are missing a new line at the end of `main.rs`
these are my versions which run totally fine:
```
rustfmt 0.8.2-stable (08da30d 2018-06-06)
rustc 1.28.0 (9634041f0 2018-07-30)
```

**Comment by deg4uss3r** [comment]
@DD5HT Thanks, didn't see that in the [contribute](https://github.com/ashleygwilliams/cargo-generate/blob/master/CONTRIBUTING.md) documentation, but fixed.

**Comment by deg4uss3r** [comment]
Let me know if there's any tests or documentation you'd like me to add and I would be happy to work on that :)

**Comment by posborne** [comment]
I didn't see this PR at first and put together some changes for this feature as it is something I ended up needing this evening.  Here's the patchset I put together: https://github.com/ashleygwilliams/cargo-generate/compare/master...posborne:add-git-branch-support?expand=1

I think the main issue with the approach in this PR is that having a hard-coded default of "master" rather than omitting the checkout parameter will break some repos that might have a different default branch on the remote than "master" (on some repos, this may be something like "develop").

Let me know if I should open up a PR with my changes (changes for tests got a bit gross, admittedly).

**Comment by deg4uss3r** [comment]
Hey!

I’m on mobile so haven’t had a proper look at the changes, but do you think for 0.2.0 it would be sufficient to make branch a required option?

**Comment by ashleygwilliams** [comment]
hey sorry for the delay @deg4uss3r - i was on vacation and am slowly catching up on all the things. i think this looks great!

that being said i do agree with @posborne that the hardcoded default branch will probably cause some issue. @posborne do you think you could rebase your solution on top of this one? i'd like to merge this and have yours be an improvement upon it- if that's possible! lemme know if you think that rebase would be too difficult to be worth it :)

**Comment by posborne** [comment]
@ashleygwilliams I can probably make a rebase work if that is the preferred approach.  I would need to open a separate PR with that.  I think my changes would replace these except for the extra print which doesn't really seem directly related to the change (https://github.com/ashleygwilliams/cargo-generate/pull/87/files#diff-137d81403bc89c5575b8f43e343d07ffR17) -- is that something we want to include with this changeset?

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/ashleygwilliams/cargo-generate/pull/94#pullrequestreview-160316324 - sorry for the extremely bad communication. if there's something else you'd like to do on the project @deg4uss3r please let me know and it is yours!

**Pull request closed without merging**
