### PR TITLE
🕴️ 0.5.1

### PR DESCRIPTION
**Pull request by EverlastingBugstopper**
cc @k0pernicus and @ashleygwilliams

### CODE REVIEW

**Comment by k0pernicus** [comment]
Thanks!

I will add the other MR for templates (#214, #218, #219, #220, ...) as well as the other changes from 9999years (#239, #241, ...)

**Comment by EverlastingBugstopper** [comment]
oops! i missed those - just tagged them as part of the 0.5.1 milestone 😄 thanks!!!

**Comment by k0pernicus** [comment]
No problem, we should be ok now ;)

**Comment by sassman** [comment]
@k0pernicus @EverlastingBugstopper 
looks good. 

Shouldn't the version increment in the `Cargo.toml` to `0.5.1` be part of this PR?

**Comment by EverlastingBugstopper** [comment]
whooopsies. yes it should! - should be there now. good catch

**Review by sassman — APPROVED** [review]
Looks like shipping 🎉

**Comment by k0pernicus** [comment]
> @k0pernicus @EverlastingBugstopper 
> 
> looks good. 
> 
> 
> 
> Shouldn't the version increment in the `Cargo.toml` to `0.5.1` be part of this PR?

Woooh, good catch! Thanks a lot 😄

**Review by sassman — APPROVED** [review]

**Comment by sassman** [comment]
@k0pernicus @ashleygwilliams do you have any objections or can we get that out the door soonish?

**Comment by k0pernicus** [comment]
Nop, I think everything is here.
Is there another stuff to generate (like archives) or can we merge it right now?

**Comment by k0pernicus** [comment]
That's it :)

Thanks everyone for your hard work 🎉 🚀

**Pull request merged**
